[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    bblanchon/ArduinoJson @ ^7.0.0
    esphome/AsyncTCP-esphome @ ^2.0.0
    esphome/ESPAsyncWebServer-esphome @ ^3.0.0

build_flags =
    -DCORE_DEBUG_LEVEL=0

board_build.filesystem = littlefs
