; ESP32 Pomodoro Timer
; Flash: pio run -t upload   Monitor: pio device monitor

[env:esp32dev]
platform    = espressif32
board       = esp32dev
framework   = arduino

monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_ARDUHAL_LOG_DEFAULT_LEVEL=0
